In [1]:
# ===========================================
# Importação das bibliotecas
# ===========================================

import warnings

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

warnings.filterwarnings("ignore")

In [3]:
# ===========================================
# Configuração dos gráficos
# ===========================================

plt.style.use("ggplot")

sns.set_theme(
    style="whitegrid",
    palette="viridis",
    font_scale=1.1
)

plt.rcParams["figure.figsize"] = (12,6)
plt.rcParams["figure.dpi"] = 120

In [4]:
# ===========================================
# Carregamento do dataset
# ===========================================

df = pd.read_csv("FIFA_World_Cup_Champions_1930_2022.csv")

In [5]:
df.head()

,year,host_country,host_city_final,stadium,winner,runner_up,winner_captain,winner_head_coach,win_method,winner_goals,...,matches_played,winner_titles_after_win,continent_winner,golden_ball,golden_boot,best_young_player,golden_glove,top_scorer_goals,mascot,official_ball
0,1930,Uruguay,Montevideo,Estadio Centenario,Uruguay,Argentina,José Nasazzi,Alberto Suppici,Regular Time,4,...,18,1,South America,NaN,Guillermo Stábile,NaN,NaN,8,NaN,T-Model
1,1934,Italy,Rome,Stadio Nazionale PNF,Italy,Czechoslovakia,Gianpiero Combi,Vittorio Pozzo,Extra Time,2,...,17,1,Europe,NaN,Oldřich Nejedlý,NaN,NaN,5,NaN,Federale 102
2,1938,France,Paris,Stade Olympique de Colombes,Italy,Hungary,Giuseppe Meazza,Vittorio Pozzo,Regular Time,4,...,18,2,Europe,NaN,Leônidas,NaN,NaN,7,NaN,Allen
3,1950,Brazil,Rio de Janeiro,Maracanã,Uruguay,Brazil,Obdulio Varela,Juan López Fontana,Regular Time,2,...,22,2,South America,NaN,Ademir,NaN,NaN,9,NaN,Super Duplo T
4,1954,Switzerland,Bern,Wankdorf Stadium,West Germany,Hungary,Fritz Walter,Sepp Herberger,Regular Time,3,...,26,1,Europe,NaN,Sándor Kocsis,NaN,NaN,11,NaN,Swiss World Champion

In [6]:
print(f'Número de linhas: {df.shape[0]}')
print(f'Número de colunas: {df.shape[1]}')

Número de linhas: 22
Número de colunas: 23

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 23 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   year                     22 non-null     int64
 1   host_country             22 non-null     str
 2   host_city_final          22 non-null     str
 3   stadium                  22 non-null     str
 4   winner                   22 non-null     str
 5   runner_up                22 non-null     str
 6   winner_captain           22 non-null     str
 7   winner_head_coach        22 non-null     str
 8   win_method               22 non-null     str
 9   winner_goals             22 non-null     int64
 10  runner_up_goals          22 non-null     int64
 11  attendance               22 non-null     int64
 12  total_teams              22 non-null     int64
 13  matches_played           22 non-null     int64
 14  winner_titles_after_win  22 non-null     int64
 15  continent_winner         22 non-null     str
 16  golden_ball              11 non-null     str
 17  golden_boot              22 non-null     str
 18  best_young_player        5 non-null      str
 19  golden_glove             8 non-null      str
 20  top_scorer_goals         22 non-null     int64
 21  mascot                   15 non-null     str
 22  official_ball            22 non-null     str
dtypes: int64(8), str(15)
memory usage: 4.1 KB

In [8]:
df.describe()

,year,winner_goals,runner_up_goals,attendance,total_teams,matches_played,winner_titles_after_win,top_scorer_goals
count,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000
mean,1978.909091,2.636364,1.136364,81534.636364,22.227273,43.818182,2.227273,7.136364
std,27.738419,1.292670,0.888844,26831.765955,7.602830,17.632860,1.231794,2.188617
min,1930.000000,0.000000,0.000000,45000.000000,13.000000,17.000000,1.000000,4.000000
25%,1959.000000,2.000000,0.250000,68759.250000,16.000000,32.000000,1.000000,6.000000
50%,1980.000000,3.000000,1.000000,76374.500000,20.000000,45.000000,2.000000,6.000000
75%,2001.000000,3.750000,2.000000,89741.500000,32.000000,64.000000,3.000000,8.000000
max,2022.000000,5.000000,3.000000,173850.000000,32.000000,64.000000,5.000000,13.000000

In [9]:
df.describe(include="object")

,host_country,host_city_final,stadium,winner,runner_up,winner_captain,winner_head_coach,win_method,continent_winner,golden_ball,golden_boot,best_young_player,golden_glove,mascot,official_ball
count,22,22,22,22,22,22,22,22,22,11,22,5,8,15,22
unique,18,19,19,9,11,22,21,3,2,10,22,5,8,15,22
top,Italy,Rome,Maracanã,Brazil,Argentina,José Nasazzi,Vittorio Pozzo,Regular Time,Europe,Lionel Messi,Guillermo Stábile,Lukas Podolski,Michel Preud'homme,World Cup Willie,T-Model
freq,2,2,2,5,3,1,2,14,12,2,1,1,1,1,1

In [11]:
for coluna in df.columns:
    print(coluna)

year
host_country
host_city_final
stadium
winner
runner_up
winner_captain
winner_head_coach
win_method
winner_goals
runner_up_goals
attendance
total_teams
matches_played
winner_titles_after_win
continent_winner
golden_ball
golden_boot
best_young_player
golden_glove
top_scorer_goals
mascot
official_ball

In [12]:
df.sample(5, random_state=42)

,year,host_country,host_city_final,stadium,winner,runner_up,winner_captain,winner_head_coach,win_method,winner_goals,...,matches_played,winner_titles_after_win,continent_winner,golden_ball,golden_boot,best_young_player,golden_glove,top_scorer_goals,mascot,official_ball
0,1930,Uruguay,Montevideo,Estadio Centenario,Uruguay,Argentina,José Nasazzi,Alberto Suppici,Regular Time,4,...,18,1,South America,NaN,Guillermo Stábile,NaN,NaN,8,NaN,T-Model
13,1990,Italy,Rome,Stadio Olimpico,West Germany,Argentina,Lothar Matthäus,Franz Beckenbauer,Regular Time,1,...,52,3,Europe,Salvatore Schillaci,Salvatore Schillaci,NaN,NaN,6,Ciao,Etrusco Unico
8,1970,Mexico,Mexico City,Estadio Azteca,Brazil,Italy,Carlos Alberto Torres,Mário Zagallo,Regular Time,4,...,32,3,South America,NaN,Gerd Müller,NaN,NaN,10,Juanito,Telstar
1,1934,Italy,Rome,Stadio Nazionale PNF,Italy,Czechoslovakia,Gianpiero Combi,Vittorio Pozzo,Extra Time,2,...,17,1,Europe,NaN,Oldřich Nejedlý,NaN,NaN,5,NaN,Federale 102
15,1998,France,Saint-Denis,Stade de France,France,Brazil,Didier Deschamps,Aimé Jacquet,Regular Time,3,...,64,1,Europe,Ronaldo,Davor Šuker,NaN,Fabien Barthez,6,Footix,Tricolore